IF NOT EXISTS (
  SELECT *
  FROM sysobjects
  WHERE name = 'TBL_CLIENTE'
    AND xtype = 'U'
) BEGIN CREATE TABLE TBL_CLIENTE(
  ID_CLIENTE UNIQUEIDENTIFIER PRIMARY Key DEFAULT NEWID(),
  CODIGO INT NOT NULL UNIQUE,
  NOME_FANTASIA VARCHAR(255) NOT NULL,
  TIPO CHAR(1) NOT NULL CHECK (TIPO IN ('F', 'J')),
  -- F = fisica e J = Juridica
  CRIADO_EM DATETIME NOT NULL DEFAULT GETDATE(),
  ALTERADO_EM DATETIME NULL,
  EXCLUIDO_EM DATETIME NULL
);
END;
IF NOT EXISTS(
  SELECT *
  FROM sysobjects
  WHERE name = 'TBL_CLIENTE_JURIDICA'
    AND xtype = 'U'
) BEGIN CREATE TABLE TBL_CLIENTE_JURIDICA(
  ID_CLIENTE_JURIDICA UNIQUEIDENTIFIER PRIMARY KEY,
  ID_CLIENTE UNIQUEIDENTIFIER NOT NULL,
  CNPJ CHAR(14) NOT NULL UNIQUE,
  RAZAO_SOCIAL VARCHAR(255) NOT NULL,
  INSCRICAO_ESTADUAL VARCHAR(50) NULL,
  CONSTRAINT FK_TBL_CLIENTE_JURIDICA_TBL_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);
END;
IF NOT EXISTS(
  SELECT *
  FROM sysobjects
  WHERE name = 'TBL_CLIENTE_FISICA'
    AND xtype = 'U'
) BEGIN CREATE TABLE TBL_CLIENTE_FISICA(
  ID_CLIENTE_FISICA UNIQUEIDENTIFIER PRIMARY KEY,
  ID_CLIENTE UNIQUEIDENTIFIER NOT NULL,
  CPF CHAR(11) NOT NULL UNIQUE,
  ID_PROFISSAO INT NULL,
  CONSTRAINT FK_TBL_CLIENTE_FISICA_TBL_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE) ON DELETE CASCADE,
  CONSTRAINT FK_TBL_CLIENTE_TBL_PROFISSAO FOREIGN KEY (ID_PROFISSAO) REFERENCES TBL_PROFISSAO(ID_PROFISSAO)
);
END;
IF NOT EXISTS(
  SELECT *
  FROM sysobjects
  WHERE name = 'TBL_PROFISSAO'
    AND xtype = 'U'
) BEGIN CREATE TABLE TBL_PROFISSAO(
  ID_PROFISSAO INT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL UNIQUE
);
END;
IF NOT EXISTS(
  SELECT *
  FROM sysobjects
  WHERE name = 'TBL_ENDERECO'
    AND xtype = 'U'
) BEGIN CREATE TABLE TBL_ENDERECO(
  ID_ENDERECO UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  ID_CLIENTE UNIQUEIDENTIFIER NOT NULL,
  LOGRADOURO VARCHAR(255) NOT NULL,
  NUMERO VARCHAR(10) NOT NULL,
  COMPLEMENTO VARCHAR(255) NULL,
  BAIRRO VARCHAR(100) NOT NULL,
  CIDADE VARCHAR(100) NOT NULL,
  ESTADO CHAR(2) NOT NULL,
  CEP CHAR(8) NOT NULL,
  FL_PRINCIPAL BIT NOT NULL DEFAULT 0,
  CONSTRAINT FK_TBL_ENDERECO_TBL_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);
END;
IF NOT EXISTS(
  SELECT *
  FROM sysobjects
  WHERE name = 'UX_ENDERECO_PRINCIPAL'
    AND xtype = 'U'
) BEGIN CREATE UNIQUE INDEX UX_ENDERECO_PRINCIPAL ON TBL_ENDERECO(ID_CLIENTE)
WHERE FL_PRINCIPAL = 1;
END;
IF NOT EXISTS(
  SELECT *
  FROM sysobjects
  WHERE name = 'TBL_CONTATO'
    AND xtype = 'U'
) BEGIN CREATE TABLE TBL_CONTATO(
  ID_CONTATO UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  ID_CLIENTE UNIQUEIDENTIFIER NOT NULL,
  TIPO CHAR(1) NOT NULL CHECK(TIPO IN('F', 'M', 'E')),
  --Telefone Fixo, Movel e EMAIL
  VALOR VARCHAR(100) NOT NULL,
  FL_PRINCIPAL BIT NOT NULL DEFAULT 0,
  CONSTRAINT FK_TBL_CONTATO_TBL_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES TBL_CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);
END;
IF NOT EXISTS(
  SELECT *
  FROM sysobjects
  WHERE name = 'UX_CONTATO_PRINCIPAL'
    AND xtype = 'U'
) BEGIN CREATE UNIQUE INDEX UX_CONTATO_PRINCIPAL ON TBL_CONTATO(ID_CLIENTE, TIPO)
WHERE FL_PRINCIPAL = 1;
END;